# Generated by Django 4.1 on 2022-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(default='no_pitcure.jpg', upload_to='produtcs')),
                ('price', models.FloatField(help_text='in US dollars $')),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
